### ISSUE TITLE
Gi Package not included within the files of the project

### ISSUE THREAD

**Issue by VerzatileDev** [orbitalmartian8/Universe#14]
**Issue listed with the project**

Consider additionally adding Gi package into the project, for it to be able to run without having the
other developers manually install it.

Documentation: < [Gi Package](https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started) > 

**Solution**

Consider adding dependencies folder within your project, which would include the package and or install it.

**Alternatives**

Publish a temporary tutorial page for others to install it instead for the time being.

**General**

The package seems to be only installed on your personal device and it would have problems in a published format " release format " in the near future and it has to be managed from the project itself.

**Comment by LinuxGamer** [comment]
Awesome stuff, thanks, either I can look into this or someone else can come forward to fix the issue.

**Comment by LinuxGamer** [comment]
Fixed (I hope)

**Comment by VerzatileDev** [comment]
Seems as the dependency for GI Library has not been added to the files of the project.  As it is not added the application Check will always fail on your GitHub, that is what the: Red "x" stands for, as it cannot compile for others, consider adding the library on the project folder or inside it and linking it to the project as it seems to me that as of currently your library is only internally installed to program files or such a like.

**Comment by LinuxGamer** [comment]
Hmm, ok, i added it to requirements.txt which should of fixed it.
